[package]
name = "jswt-derive"
version = "0.1.0"
authors = ["Nish Tahir <nishtahir@outlook.com>"]
edition = "2018"

[lib]
doctest = false
proc-macro = true


[dependencies]
jswt-common = {path = "../jswt-common"}
syn = { version = "2.0.2", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"